[package]
name = "spread_bot"
version = "0.1.0"
authors = ["Nick Vincent <emailnjv@gmail.com>"]

[dependencies]
log = "0.4.0"
env_logger = "0.6.0"
serde_json = "1.0"
serde="1.0"
serde_derive = "1.0.80"

[dependencies.ws]
version = "*"
features = ["ssl"]